/**
 * Step 11: Create GitHub issue from spec.
 */
import type { PipelineStep, GenesisPayload, CreatedIssue } from "../types.js";
import { DEFAULT_WORKFLOW, getLabelColors } from "../../workflow/index.js";
import { loadConfig } from "../../config/index.js";

/** Build issue body from spec. */
function buildIssueBody(payload: GenesisPayload): string {
  const spec = payload.spec!;
  const sections: string[] = [];

  sections.push(`## Objetivo\n\n${spec.objective}`);
  sections.push(`## Escopo V1\n\n${spec.scope_v1.map(s => `- ${s}`).join("\n")}`);

  if (spec.out_of_scope.length > 0) {
    sections.push(`## Fora de escopo\n\n${spec.out_of_scope.map(s => `- ${s}`).join("\n")}`);
  }

  sections.push(`## Acceptance Criteria\n\n${spec.acceptance_criteria.map(s => `- [ ] ${s}`).join("\n")}`);
  sections.push(`## Definition of Done\n\n${spec.definition_of_done.map(s => `- [ ] ${s}`).join("\n")}`);

  if (spec.constraints && spec.constraints !== "None specified") {
    sections.push(`## Constraints\n\n${spec.constraints}`);
  }

  if (spec.risks.length > 0) {
    sections.push(`## Risks\n\n${spec.risks.map(s => `- ${s}`).join("\n")}`);
  }

  if (payload.qa_contract) {
    sections.push(`## QA Contract\n\nQA contract generated with ${payload.qa_contract.gates.length} gates. Canonical QA Evidence must be posted in the PR body.`);
  }

  sections.push(`---\n_Generated by Genesis Pipeline (session: ${payload.session_id})_`);

  return sections.join("\n\n");
}

export const createTaskStep: PipelineStep = {
  name: "create-task",

  shouldRun: (payload) =>
    !!payload.spec &&
    !payload.dry_run &&
    payload.metadata?.project_registered === true &&
    Boolean(
      payload.provisioning?.repo_local
      || payload.provisioning?.repo_url
      || payload.scaffold?.repo_local
      || payload.scaffold?.repo_url
      || payload.metadata?.repo_path
      || payload.metadata?.repo_url,
    ),

  async execute(payload, ctx): Promise<GenesisPayload> {
    if (payload.metadata?.project_registered !== true) {
      throw new Error("Project must be registered successfully before issue creation");
    }

    const spec = payload.spec!;
    ctx.log(`Creating issue: "${spec.title}"`);

    const repoUrl = payload.provisioning?.repo_url ?? payload.scaffold?.repo_url ?? payload.metadata?.repo_url;
    const repoPath =
      payload.provisioning?.repo_local
      ?? payload.scaffold?.repo_local
      ?? payload.metadata?.repo_path
      ?? payload.project_map?.root
      ?? undefined;
    const projectSlug = payload.metadata?.project_slug ?? payload.scaffold?.project_slug ?? payload.project_map?.project_slug;
    const resolvedConfig = await loadConfig(ctx.workspaceDir, projectSlug ?? undefined);
    const initialLabel =
      resolvedConfig.workflow.states[resolvedConfig.workflow.initial]?.label
      ?? DEFAULT_WORKFLOW.states[DEFAULT_WORKFLOW.initial]?.label
      ?? "Planning";
    const initialLabelColor =
      getLabelColors(resolvedConfig.workflow)[initialLabel]
      ?? getLabelColors(DEFAULT_WORKFLOW)[initialLabel]
      ?? "#95a5a6";

    const body = buildIssueBody(payload);
    const title = spec.title;

    if (ctx.createIssueProvider && repoPath) {
      const { provider } = await ctx.createIssueProvider({
        repoPath,
        projectSlug,
      });
      await provider.ensureLabel(initialLabel, initialLabelColor);
      const created = await provider.createIssue(title, body, initialLabel);
      const issue: CreatedIssue = {
        number: created.iid,
        url: created.web_url,
        created_at: new Date().toISOString(),
      };

      ctx.log(`Issue created via provider: #${issue.number} — ${issue.url}`);

      return {
        ...payload,
        step: "create-task",
        issues: [issue],
      };
    }

    if (!repoUrl) {
      throw new Error("No repo URL available for compatibility fallback issue creation");
    }

    // Compatibility fallback when the step context does not provide provider access.
    const match = repoUrl.match(/github\.com[/:]([^/]+\/[^/.]+)/);
    const ownerRepo = match?.[1] ?? repoUrl;

    const result = await ctx.runCommand("gh", [
      "issue", "create",
      "--repo", ownerRepo,
      "--title", title,
      "--body", body,
      "--label", initialLabel,
    ], { timeout: 30000 });

    if (result.exitCode !== 0) {
      throw new Error(`Failed to create issue: ${result.stderr}`);
    }

    const issueUrl = result.stdout.trim();
    const numberMatch = issueUrl.match(/\/(\d+)$/);
    const issueNumber = numberMatch ? parseInt(numberMatch[1], 10) : 0;

    const issue: CreatedIssue = {
      number: issueNumber,
      url: issueUrl,
      created_at: new Date().toISOString(),
    };

    ctx.log(`Issue created via compatibility fallback: #${issueNumber} — ${issueUrl}`);

    return {
      ...payload,
      step: "create-task",
      issues: [issue],
    };
  },
};
